DROP TABLE IF EXISTS Items;
DROP TABLE IF EXISTS Categories;
DROP TABLE IF EXISTS Bids;
DROP TABLE IF EXISTS Users;

CREATE TABLE Items(
    ItemID INTEGER PRIMARY KEY,
    Name STRING,
    Currently REAL,
    Buy_Price REAL,
    First_Bid REAL,
    Number_of_Bids INTEGER,
    Started STRING, 
    Ends STRING,
    UserID STRING,
    Description STRING,
    FOREIGN KEY(UserID) REFERENCES Users(UserID) DEFERRABLE INITIALLY DEFERRED
 );
 
CREATE TABLE Categories(
    Name STRING,
    ItemID INTEGER,
    FOREIGN KEY(ItemID) REFERENCES Items(ItemID) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE Bids(
    ItemID INTEGER,   
    UserID STRING,
    Time STRING,
    Amount STRING,
    FOREIGN KEY(ItemID) REFERENCES Items(ItemID) DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY(UserID) REFERENCES Users(UserID) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE Users(
    UserID STRING PRIMARY KEY, 
    Rating REAL,
    Location STRING,
    Country STRING  
);